export const PLAYSTATE_INIT = 'PLAYSTATE_INIT'
export const PLAYSTATE_PLAYING = 'PLAYSTATE_PLAYING'
export const PLAYSTATE_PAUSED = 'PLAYSTATE_PAUSED'
export const PLAYSTATE_ENDED = 'PLAYSTATE_ENDED'
